# Nginx server configuration for React app.
server {
    # Nginx listens on port 80 inside Docker.
    listen 80;

    # Website files are stored here inside the container.
    root /usr/share/nginx/html;

    # Main React file.
    index index.html;

    # This helps React routes work after refresh.
    location / {
        try_files $uri $uri/ /index.html;
    }
}